# --- STAGE 1: Builder ---

FROM node:20-slim AS build-stage

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

# --- STAGE 2: Runtime ---

FROM nginx:stable-alpine

# Copy the built files from vite's default dist folder
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]